export const AUTH_SUCCESS = 'AUTH_SUCCESS'
export const AUTH_FAILURE = 'AUTH_FAILURE'
export const RESET_STATE = 'RESET_STATE'
export const CURRENT_NOTE = 'CURRENT_NOTE'
export const ADD_NOTE = 'ADD_NOTE'
export const RENDER_NOTES = 'RENDER_NOTES'
export const UPDATE_NOTE = 'UPDATE_NOTE'
